---
title: "Writing an R package with Rstudio and Github"
author: "Shaun Wilkinson"
date: "Sunday, December 20, 2015"
output: html_document
---

To configure settings open command prompt and run the following commands:
git config -global user.name "shaunpwilkinson"
git config -global user.email "shaunpwilkinson@gmail.com"

Set path to Git executable file. In RStudio select Tools > Global options, 
select Git/SVN and type file path in Git executable feild.
Windows example 
C:/Program Files (x86)/Git/bin/git.exe 
Linux/mac example
/usr/bin/git


If creating new repo
log into GitHub and create a new repository. check the 
'Initialize this repository with a README' box and enter a short description
about the package

Copy the path to the repository (e.g https://github.com/shaunpwilkinson/pHMM.git)

Create a new project in RStudio. Select File > New Project > Version Control
Select Git (clone a project from a Git repository) and paste the web address into the 
Repository URL field. The Project directory name should update automatically. Choose 
where to place the new clone folder in the 'create as a subdirectory of' field (e.g. browse to ~/Desktop).

Commit changes: Select the Git tab and check all boxes, select Commit, and type a commit
message in the field. Select Commit. Click on the Push button (green up-arrow) to push 
changes to Github (must be connected to the internet for this).

Optional: Add ignorable folder(s). Eg if you want a folder called Shaun to be ignored when
the R package is compiled, add the line ^Shaun$ to the .Rbuildignore file

Setup package files/folders including DESCRIPTION, NAMESPACE, .gitignore and .Rbuildignore 
files and the R folder. The easiest way to do this is to run the create function in 
the devtools package (e.g. devtools::create("pHMM")). The problem is that this creates a new 
pHMM folder in the original pHMM repository. Copy the files into the original folder and
delete the new one. 
Ensure that in the DESCRIPTION file has the line Lazydata: TRUE. This is done by default in 
devtools::create 

Useful links:
The essential guide 'R Packages' by Hadley Wickham
<http://r-pkgs.had.co.nz/>

A helpful post on the Molecular Ecologist by Mark Christie 
<http://www.molecularecologist.com/2013/11/using-github-with-r-and-rstudio/>


