// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ViterbiHMM
List ViterbiHMM(List x, CharacterVector y, bool logspace);
RcppExport SEXP profile_ViterbiHMM(SEXP xSEXP, SEXP ySEXP, SEXP logspaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type logspace(logspaceSEXP);
    __result = Rcpp::wrap(ViterbiHMM(x, y, logspace));
    return __result;
END_RCPP
}
// ViterbiPHMM
List ViterbiPHMM(List x, CharacterVector y, bool logspace);
RcppExport SEXP profile_ViterbiPHMM(SEXP xSEXP, SEXP ySEXP, SEXP logspaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type logspace(logspaceSEXP);
    __result = Rcpp::wrap(ViterbiPHMM(x, y, logspace));
    return __result;
END_RCPP
}
