// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Viterbidefault
List Viterbidefault(IntegerVector x, IntegerVector y, int type, double d, double e, NumericMatrix S, LogicalMatrix itertab, double offset);
RcppExport SEXP profile_Viterbidefault(SEXP xSEXP, SEXP ySEXP, SEXP typeSEXP, SEXP dSEXP, SEXP eSEXP, SEXP SSEXP, SEXP itertabSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type e(eSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type S(SSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type itertab(itertabSEXP);
    Rcpp::traits::input_parameter< double >::type offset(offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(Viterbidefault(x, y, type, d, e, S, itertab, offset));
    return rcpp_result_gen;
END_RCPP
}
// ViterbiHMM
List ViterbiHMM(List x, CharacterVector y, bool logspace);
RcppExport SEXP profile_ViterbiHMM(SEXP xSEXP, SEXP ySEXP, SEXP logspaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type logspace(logspaceSEXP);
    rcpp_result_gen = Rcpp::wrap(ViterbiHMM(x, y, logspace));
    return rcpp_result_gen;
END_RCPP
}
// ViterbiPHMM
List ViterbiPHMM(List x, CharacterVector y, bool logspace);
RcppExport SEXP profile_ViterbiPHMM(SEXP xSEXP, SEXP ySEXP, SEXP logspaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type logspace(logspaceSEXP);
    rcpp_result_gen = Rcpp::wrap(ViterbiPHMM(x, y, logspace));
    return rcpp_result_gen;
END_RCPP
}
// kdist
NumericVector kdist(List x, int k, bool asmatrix);
RcppExport SEXP profile_kdist(SEXP xSEXP, SEXP kSEXP, SEXP asmatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type asmatrix(asmatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(kdist(x, k, asmatrix));
    return rcpp_result_gen;
END_RCPP
}
// kdistDNA
NumericVector kdistDNA(List x, int k, bool asmatrix);
RcppExport SEXP profile_kdistDNA(SEXP xSEXP, SEXP kSEXP, SEXP asmatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type asmatrix(asmatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(kdistDNA(x, k, asmatrix));
    return rcpp_result_gen;
END_RCPP
}
// logsum
double logsum(NumericVector x);
RcppExport SEXP profile_logsum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(logsum(x));
    return rcpp_result_gen;
END_RCPP
}
// forwardC
List forwardC(List x, CharacterVector y, bool logspace);
RcppExport SEXP profile_forwardC(SEXP xSEXP, SEXP ySEXP, SEXP logspaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type logspace(logspaceSEXP);
    rcpp_result_gen = Rcpp::wrap(forwardC(x, y, logspace));
    return rcpp_result_gen;
END_RCPP
}
// backwardC
List backwardC(List x, CharacterVector y, bool logspace);
RcppExport SEXP profile_backwardC(SEXP xSEXP, SEXP ySEXP, SEXP logspaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type logspace(logspaceSEXP);
    rcpp_result_gen = Rcpp::wrap(backwardC(x, y, logspace));
    return rcpp_result_gen;
END_RCPP
}
// mapC
LogicalVector mapC(NumericMatrix ecs, LogicalMatrix notgaps, List pseudocounts, NumericVector seqweights, NumericVector qe, double lambda);
RcppExport SEXP profile_mapC(SEXP ecsSEXP, SEXP notgapsSEXP, SEXP pseudocountsSEXP, SEXP seqweightsSEXP, SEXP qeSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ecs(ecsSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type notgaps(notgapsSEXP);
    Rcpp::traits::input_parameter< List >::type pseudocounts(pseudocountsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type seqweights(seqweightsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type qe(qeSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(mapC(ecs, notgaps, pseudocounts, seqweights, qe, lambda));
    return rcpp_result_gen;
END_RCPP
}
// returnmod
List returnmod(List x);
RcppExport SEXP profile_returnmod(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(returnmod(x));
    return rcpp_result_gen;
END_RCPP
}
// transitioncount
IntegerVector transitioncount(IntegerVector x, int numbersystem);
RcppExport SEXP profile_transitioncount(SEXP xSEXP, SEXP numbersystemSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type numbersystem(numbersystemSEXP);
    rcpp_result_gen = Rcpp::wrap(transitioncount(x, numbersystem));
    return rcpp_result_gen;
END_RCPP
}
// emissioncount
IntegerVector emissioncount(IntegerVector states, int statenumbersystem, IntegerVector residues, int resnumbersystem);
RcppExport SEXP profile_emissioncount(SEXP statesSEXP, SEXP statenumbersystemSEXP, SEXP residuesSEXP, SEXP resnumbersystemSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type states(statesSEXP);
    Rcpp::traits::input_parameter< int >::type statenumbersystem(statenumbersystemSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type residues(residuesSEXP);
    Rcpp::traits::input_parameter< int >::type resnumbersystem(resnumbersystemSEXP);
    rcpp_result_gen = Rcpp::wrap(emissioncount(states, statenumbersystem, residues, resnumbersystem));
    return rcpp_result_gen;
END_RCPP
}
// tab9C
NumericMatrix tab9C(IntegerMatrix x, NumericVector seqweights);
RcppExport SEXP profile_tab9C(SEXP xSEXP, SEXP seqweightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type seqweights(seqweightsSEXP);
    rcpp_result_gen = Rcpp::wrap(tab9C(x, seqweights));
    return rcpp_result_gen;
END_RCPP
}
// DNA2pentadecimal
IntegerVector DNA2pentadecimal(RawVector x);
RcppExport SEXP profile_DNA2pentadecimal(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(DNA2pentadecimal(x));
    return rcpp_result_gen;
END_RCPP
}
// DNAprobC
double DNAprobC(RawVector a, NumericVector probs);
RcppExport SEXP profile_DNAprobC(SEXP aSEXP, SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type probs(probsSEXP);
    rcpp_result_gen = Rcpp::wrap(DNAprobC(a, probs));
    return rcpp_result_gen;
END_RCPP
}
