print.PHMM <- function(x){
  cat("Profile hidden Markov model (object class: 'PHMM')\n",
      "with ",
      x$size,
      " internal positions emitting ",
      nrow(x$E),
      " unique residues\n",
      "(",
      paste(rownames(x$E), collapse = ", "),
      ").\n",
      sep = "")
}

print.HMM <- function(x){
  cat("Hidden Markov model (object class: 'HMM') with ",
      nrow(x$E),
      " hidden states (",
      paste(rownames(x$E), collapse = ", "),
      ") emitting ",
      ncol(x$E),
      " unique residues (",
      paste(colnames(x$E), collapse = ", "),
      ").\n",
      sep = "")
}


print.forward <- function(x){
  cat("Full (log) probability or log-odds score of observed sequence having
      been generated by the model: ",
      x$score)
}
#
# print.alignment <- function(x){
#   cat("Alignment of",
#       nrow(x$alignment),
#       "sequences with score",
#       x$score)
# }

print.backward <- function(x){
  cat("Full (log) probability or log-odds score of observed sequence having
      been generated by the model: ",
      x$score)
}

print.Viterbi <- function(x){
  cat("Optimal Viterbi path with length",
      length(x$path),
      "and score",
      x$score)
}
