# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Optimal path of sequence through model.
#'
#' \code{ViterbiC} finds the optimal path of a sequence through a HMM
#' or PHMM and returns its log-odds score.
#'
#' @param x an object of class \code{HMM} or \code{PHMM}, or a character vector.
#' @param y a character vector consisting of residues emitted by the
#' HMM or PHMM.
#' @param logspace logical argument indicating whether the emission
#' and transmission probabilities for the model(s) are logged.
#' @name ViterbiC
#' @export
ViterbiC.HMM <- function(x, y, logspace = FALSE) {
    .Call('profile_ViterbiHMM', PACKAGE = 'profile', x, y, logspace)
}

#' @rdname ViterbiC
#' @export
ViterbiC.PHMM <- function(x, y, logspace = FALSE) {
    .Call('profile_ViterbiPHMM', PACKAGE = 'profile', x, y, logspace)
}

#' Full log probability of sequence given model.
#'
#' Implementation of the forward algorithm to caluclate the full (log) probability
#' of a sequence through a given a HMM or profile HMM.
#' @param x an object of class \code{HMM} or \code{PHMM}.
#'
logsum <- function(x) {
    .Call('profile_logsum', PACKAGE = 'profile', x)
}

forwardC <- function(x, y, logspace = FALSE) {
    .Call('profile_forwardC', PACKAGE = 'profile', x, y, logspace)
}

backwardC <- function(x, y, logspace = FALSE) {
    .Call('profile_backwardC', PACKAGE = 'profile', x, y, logspace)
}

returnmod <- function(x) {
    .Call('profile_returnmod', PACKAGE = 'profile', x)
}

tab9C <- function(x, modules) {
    .Call('profile_tab9C', PACKAGE = 'profile', x, modules)
}

